apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
 labels:
   kops.k8s.io/cluster: test.devtron.k8s.local
 name: spot-nodes-xlarge
spec:
 image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2020-07-20
 machineType: c3.xlarge
 maxSize: 10
 minSize: 0
 mixedInstancesPolicy:
   instances:
   - c3.xlarge
   - c4.xlarge
   - c5.xlarge
   - c5a.xlarge
   onDemandAboveBase: 0
   onDemandBase: 0
   spotAllocationStrategy: capacity-optimized
 nodeLabels:
   kops.k8s.io/instancegroup: spot-nodes-xlarge
   lifecycle: "spot"
 role: Node
 subnets:
 - us-east-1a
 - us-east-1b
 - us-east-1c
